IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PRC_GEN_RPT_LIQ_DET')
BEGIN
    DROP PROCEDURE PRC_GEN_RPT_LIQ_DET;
END
GO

CREATE PROCEDURE PRC_GEN_RPT_LIQ_DET
    @ANIO_DESDE INT,
	@MES_DESDE INT,
	@ANIO_HASTA INT,
	@MES_HASTA INT
AS
BEGIN
SELECT DESCRIPCION,ANIO,MES,SUM(HM)HABER_MENSUAL,SUM(TITULO) TITULO 
	FROM(	
	SELECT LIQ.ID,LIQ.descripcion,LIQ.ANIO,LIQ.MES,C.nombre,
		CASE 
			WHEN C.nombre = 'Haber mensual' THEN SUM(TC.monto)
		ELSE 0
		END as 'HM',
		CASE 
			WHEN C.nombre = 'Titulo' THEN SUM(TC.monto)
		ELSE 0
		END 'TITULO'
	FROM LIQUIDACION LIQ
	JOIN Tabulado T ON T.ID_LIQUIDACION=LIQ.id
	JOIN TABULADO_CONCEPTO TC ON TC.ID_TABULADO =T.id
	JOIN CONCEPTO C ON C.id=TC.ID_CONCEPTO
	WHERE ANIO > @ANIO_DESDE AND ANIO < @ANIO_HASTA
	AND MES > @MES_DESDE AND MES < @MES_HASTA 
	GROUP BY LIQ.ID,LIQ.descripcion,LIQ.ANIO,LIQ.MES,C.nombre
	)TABLA
	GROUP BY DESCRIPCION,ANIO,MES
END;
