IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'PRC_GEN_RPT_LIQ')
BEGIN
    DROP PROCEDURE PRC_GEN_RPT_LIQ;
END
GO

CREATE PROCEDURE PRC_GEN_RPT_LIQ
    @ANIO_DESDE INT,
	@MES_DESDE INT,
	@ANIO_HASTA INT,
	@MES_HASTA INT
AS
BEGIN
	SELECT LIQ.ID,LIQ.descripcion,LIQ.ANIO,LIQ.MES,SUM(T.ID) TABULADOS,SUM(TC.monto) MONTO 
	FROM LIQUIDACION LIQ
	JOIN Tabulado T ON T.ID_LIQUIDACION=LIQ.id
	JOIN TABULADO_CONCEPTO TC ON TC.ID_TABULADO =T.id
	JOIN CONCEPTO C ON C.id=TC.ID_CONCEPTO
	WHERE (ANIO*12+MES) > @ANIO_DESDE*12+@MES_DESDE AND (ANIO*12+MES) < (@ANIO_HASTA*12+@MES_HASTA)
	AND TC.SENTIDO='D'
	GROUP BY LIQ.ID,LIQ.descripcion,LIQ.ANIO,LIQ.MES,T.ID
	ORDER BY LIQ.ID,LIQ.descripcion,LIQ.ANIO,LIQ.MES,T.ID
END;
